version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: database

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d database"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring-net

  backend:
    image: ikrashbakhsh/backend:latest
    container_name: backend
    restart: always

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: "1234"
      DB_NAME: database

    ports:
      - "5000:5000"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring-net

  frontend:
    image: ikrashbakhsh/frontend:latest
    container_name: frontend
    restart: always

    depends_on:
      backend:
        condition: service_healthy
    networks:
      - monitoring-net

  nginx:
    image: ikrashbakhsh/nginx:latest
    container_name: nginx
    restart: always

    depends_on:
      frontend:
        condition: service_started

    ports:
      - "80:80"
    networks:
      - monitoring-net

volumes:
  postgres_data:

networks:
  monitoring-net:
    external: true