services:
  frontend:
    build: ikrashbakhsh/frontend:v1
    container_name: frontend
    depends_on:
      - backend

  backend:
    build: ikrashbakhsh/backend:v1
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres
      DB_USER: admin
      DB_PASSWORD: "1234"
      DB_NAME: database

  nginx:
    build: ikrashbakhsh/nginx:v1
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: