events {
    worker_connections 1024;
}

http {

    upstream frontend {
        server frontend:100;
    }

    upstream backend {
        server backend:5000;
    }

    server {
        listen 100;

        location / {
            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_pass http://backend;
        }
    }
}